config/routes.rb
Rails.application.routes.draw do
  resources :barangs
  resources :homeworks
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/barang.rb
class Barang < ApplicationRecord
end

app/models/homework.rb
class Homework < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/barangs_controller.rb
class BarangsController < ApplicationController
  before_action :set_barang, only: %i[ show edit update destroy ]

  # GET /barangs or /barangs.json
  def index
    @barangs = Barang.all
  end

  # GET /barangs/1 or /barangs/1.json
  def show
  end

  # GET /barangs/new
  def new
    @barang = Barang.new
  end

  # GET /barangs/1/edit
  def edit
  end

  # POST /barangs or /barangs.json
  def create
    @barang = Barang.new(barang_params)

    respond_to do |format|
      if @barang.save
        format.html { redirect_to barang_url(@barang), notice: "Barang was successfully created." }
        format.json { render :show, status: :created, location: @barang }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @barang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barangs/1 or /barangs/1.json
  def update
    respond_to do |format|
      if @barang.update(barang_params)
        format.html { redirect_to barang_url(@barang), notice: "Barang was successfully updated." }
        format.json { render :show, status: :ok, location: @barang }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @barang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barangs/1 or /barangs/1.json
  def destroy
    @barang.destroy

    respond_to do |format|
      format.html { redirect_to barangs_url, notice: "Barang was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barang
      @barang = Barang.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def barang_params
      params.require(:barang).permit(:nama, :jenis, :bahan)
    end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: %i[ show edit update destroy ]

  # GET /homeworks or /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1 or /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks or /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to homework_url(@homework), notice: "Homework was successfully created." }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1 or /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to homework_url(@homework), notice: "Homework was successfully updated." }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1 or /homeworks/1.json
  def destroy
    @homework.destroy

    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: "Homework was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def homework_params
      params.require(:homework).permit(:homework_name, :category, :deadline, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barangs_helper.rb
module BarangsHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/barangs/_barang.html.erb
<div id="<%= dom_id barang %>">
  <p>
    <strong>Nama:</strong>
    <%= barang.nama %>
  </p>

  <p>
    <strong>Jenis:</strong>
    <%= barang.jenis %>
  </p>

  <p>
    <strong>Bahan:</strong>
    <%= barang.bahan %>
  </p>

</div>

app/views/barangs/_form.html.erb
<%= form_with(model: barang) do |form| %>
  <% if barang.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(barang.errors.count, "error") %> prohibited this barang from being saved:</h2>

      <ul>
        <% barang.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nama, 'Nama Barang', style: "display: block" %>
    <%= form.text_area :nama %>
  </div>

  <div>
    <%= form.label :jenis, 'Jenis Barang' ,style: "display: block" %>
    <%= form.text_field :jenis %>
  </div>

  <div>
    <%= form.label :bahan, style: "display: block" %>
    <%= form.text_field :bahan %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/barangs/edit.html.erb
<h1>Editing barang</h1>

<%= render "form", barang: @barang %>

<br>

<div>
  <%= link_to "Show this barang", @barang %> |
  <%= link_to "Back to barangs", barangs_path %>
</div>

app/views/barangs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Barangs</h1>

<div id="barangs">
  <% @barangs.each do |barang| %>
    <%= render barang %>
    <p>
      <%= link_to "Show this barang", barang %>
    </p>
  <% end %>
</div>

<%= link_to "New barang", new_barang_path %>

app/views/barangs/new.html.erb
<h1>New barang</h1>

<%= render "form", barang: @barang %>

<br>

<div>
  <%= link_to "Back to barangs", barangs_path %>
</div>

app/views/barangs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @barang %>

<div>
  <%= link_to "Edit this barang", edit_barang_path(@barang) %> |
  <%= link_to "Back to barangs", barangs_path %>

  <%= button_to "Destroy this barang", @barang, method: :delete %>
</div>

app/views/homeworks/_form.html.erb
<%= form_with(model: homework) do |form| %>
  <% if homework.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
        <% homework.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :homework_name, style: "display: block" %>
    <%= form.text_area :homework_name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :deadline, style: "display: block" %>
    <%= form.date_field :deadline %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/homeworks/_homework.html.erb
<div id="<%= dom_id homework %>">
  <p>
    <strong>Homework name:</strong>
    <%= homework.homework_name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= homework.category %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= homework.deadline %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= homework.description %>
  </p>

</div>

app/views/homeworks/edit.html.erb
<h1>Editing homework</h1>

<%= render "form", homework: @homework %>

<br>

<div>
  <%= link_to "Show this homework", @homework %> |
  <%= link_to "Back to homeworks", homeworks_path %>
</div>

app/views/homeworks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Homeworks</h1>

<div id="homeworks">
  <% @homeworks.each do |homework| %>
    <%= render homework %>
    <p>
      <%= link_to "Show this homework", homework %>
    </p>
  <% end %>
</div>

<%= link_to "New homework", new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New homework</h1>

<%= render "form", homework: @homework %>

<br>

<div>
  <%= link_to "Back to homeworks", homeworks_path %>
</div>

app/views/homeworks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @homework %>

<div>
  <%= link_to "Edit this homework", edit_homework_path(@homework) %> |
  <%= link_to "Back to homeworks", homeworks_path %>

  <%= button_to "Destroy this homework", @homework, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>